Repository vuejs/awesome-vue, pull requests merged in 2020-03, with the labels that each got.

#2964 Add vue-spinners-css
  README.md
Labels: git: no conflicts resolved

#3062 Added vue-keypress
  README.md
Labels: lists: not the last on the list

#2950 Vue Rest Resource
  README.md
Labels: lists: not the last on the list

#3082 docs(*): add vue-h5-audio-controls
  README.md
Labels: git: no conflicts resolved

#3045 Add vue-burger-button, vue-form-container, vue-flipper, vue-loadable and vue-uuid
  README.md
Labels: git: no conflicts resolved

#3091 Added vue-expenses, an open source expense tracking app built with vuejs and .net core
  README.md
Labels: git: no conflicts resolved

#3117 Add vue-request-store Plugin
  README.md
Labels: git: no conflicts resolved

#3139 Add Equal UI
  README.md
Labels: git: no conflicts resolved

#3128 Add element-tiptap rich-text-editor repo
  README.md
Labels: git: no conflicts resolved

#3137 feat: add massCode app
  README.md
Labels: lists: not the last on the list

#3156 Updated readme with new UI library
  README.md
Labels: git: no conflicts resolved

#3106 add vue-aspect-ratio component in Miscellaneous section
  README.md
Labels: git: no conflicts resolved

#3122 ADD @fracto/vue-credit-card
  README.md
Labels: lists: not the last on the list

#3084 feat: add vue-smart-widget
  README.md
Labels: git: no conflicts resolved

#3142 Add PrimeVue #3074
  README.md
Labels: git: no conflicts resolved

#3217 Added "vuex-loopback"
  README.md
Labels: git: no conflicts resolved

#3103 Add vuex-state-snapshot
  README.md
Labels: git: no conflicts resolved

#3228 Add Vue Cat Carousel and Blibli as an enterprice usage
  README.md
Labels: invalid

#3154 add vue-container-query-2
  README.md
Labels: lists: not the last on the list

#3192 Add vue-injector
  README.md
Labels: git: no conflicts resolved

#3155 Add website to README.md
  README.md
Labels: lists: not the last on the list

#3191 Add Akaunting
  README.md
Labels: git: no conflicts resolved

#3229 add ERD Editor
  README.md
Labels: git: no conflicts resolved

#3148 Add vue-tinybox
  README.md
Labels: git: no conflicts resolved

#3227 added VueFront to readme
  README.md
Labels: git: no conflicts resolved

#3232 replace my old vue-draggable-nested-tree with he-tree-vue; add my new vue-colrow
  README.md
Labels: invalid

#3105 Add vue-gridmultiselect
  README.md
Labels: lists: not the last on the list

#3113 Adding a tutorial for pre-rendering Vue apps using Nuxt.js
  README.md
Labels: git: no conflicts resolved

#3225 added Mockup-server
  README.md
Labels: git: no conflicts resolved

#3107 Update README.md
  README.md
Labels: lists: not the last on the list

#3141 Added component to select data (vue-select-sides)
  README.md
Labels: lists: not the last on the list

#3223 add documentary about Vue.js history
  README.md
Labels: git: no conflicts resolved

#3130 Add VueUse
  README.md
Labels: git: no conflicts resolved

#3190 Add `query-builder-vue`
  README.md
Labels: git: no conflicts resolved

#3134 Added vue-css-doodle to CSS
  README.md
Labels: git: no conflicts resolved

#2952 Adding RSVP Keeper to the Apps/Websites section
  README.md
Labels: git: no conflicts resolved

#3214 Add vue-preloaders
  README.md
Labels: git: no conflicts resolved

#3078 Add MQTTX
  README.md
Labels: git: no conflicts resolved

#3145 add vue-simple-password-meter
  README.md
Labels: git: no conflicts resolved

#3110 Update README.md
  README.md
Labels: git: no conflicts resolved

#3218 Add DataFormsJS
  README.md
Labels: git: no conflicts resolved

#3050 Add pychat and vue-webpack-typescript
  README.md
Labels: invalid

#3172 docs(readme.md): update README.md
  README.md
Labels: git: no conflicts resolved

#3167 add: pseudo-window 👻
  README.md
Labels: git: no conflicts resolved

#3168 add: Subslot 💍
  README.md
Labels: git: no conflicts resolved

#3008 Adding BMWUSA Vehicle Configurator
  README.md
Labels: lists: not the last on the list

#3143 Update README.md
  README.md
Labels: lists: not the last on the list

#3068 [Animation] New entry – v-number
  README.md
Labels: git: no conflicts resolved

#3166 Testing section
  README.md
Labels: git: no conflicts resolved, lists: not the last on the list

#3237 Add `vue-core-video-player` plugin
  README.md
Labels: lists: not the last on the list

#3025 Add `vue-plugin-events`
  README.md
Labels: lists: not the last on the list

#3236 Update README.md, add super.ba
  README.md
Labels: git: no conflicts resolved

#3210 Adds Fanmio.com
  README.md
Labels: git: no conflicts resolved

#3026 Added vue-msal plugin
  README.md
Labels: git: no conflicts resolved

#3160 Add vue-meeting-selector
  README.md
Labels: git: no conflicts resolved

#2943 Removed broken links
  README.md
Labels: invalid

#2774 adding hasura tutorials
  README.md
Labels: git: no conflicts resolved

#2778 add laranuxt and oneconcern
  README.md
Labels: git: no conflicts resolved

#2837 Added AtomicWallet apps
  README.md
Labels: git: no conflicts resolved

#2934 Description added for the Vue.js boilerplate
  README.md
Labels: git: broken PR

#2935 [New] vue-notification from @mathieustan
  README.md
Labels: git: no conflicts resolved

#2940 add vue-material-design-ripple
  README.md
Labels: lists: not the last on the list

#2958 added vue-fontawesome-picker
  README.md
Labels: git: no conflicts resolved

#2961 add vue-player
  README.md
Labels: lists: not the last on the list

#2985 Updated commercial application list
  README.md
Labels: git: no conflicts resolved

#2990 vue-pincode-input added to Form / Pincode Input
  README.md
Labels: invalid

#2995 add vue-accessible-modal
  README.md
Labels: git: no conflicts resolved

#2996 Added Helpninja in Apps
  README.md
Labels: git: no conflicts resolved

#3000 Add vue-web-cam repository
  README.md
Labels: git: no conflicts resolved

#3001 Added TodoDev in Apps/Website
  README.md
Labels: git: no conflicts resolved

#3004 Add bs-vue-timeline
  README.md
Labels: lists: not the last on the list

#3007 Included the link to push notifications for Vuejs chat app
  README.md
Labels: git: no conflicts resolved

#3011 Add Vue.js USA meetups
  README.md
Labels: git: no conflicts resolved

#3024 Update README.md with 36 Pixels
  README.md
Labels: git: no conflicts resolved

#3030 Added Servue Package to ServerSide Rendering
  README.md
Labels: git: link not to repository

#3033 added social media example
  README.md
Labels: git: no conflicts resolved

#3037 add Time Door
  README.md
Labels: git: no conflicts resolved

#3043 Update README.md
  README.md
Labels: git: no conflicts resolved

#3044 Add Open Source
  README.md
Labels: git: no conflicts resolved

#3049 Add vue-card-swipe component
  README.md
Labels: git: no conflicts resolved

#3055 add nordschool's tutorials
  README.md
Labels: git: no conflicts resolved

#3132 Added vue-cursor-fx to Miscellaneous
  README.md
Labels: lists: not the last on the list

#3056 Add vuex-test-utils
  README.md
Labels: lists: not the last on the list

#3057 Add vuex-awesome-async
  README.md
Labels: git: no conflicts resolved

#3060 Added miniPress to the list
  README.md
Labels: git: no conflicts resolved

#3061 Adde Vue Autosizer to Form category
  README.md
Labels: git: no conflicts resolved

#3064 Added Zeithub
  README.md
Labels: git: no conflicts resolved

#3066 Added PrimitiveSocial/ps-validation package
  README.md
Labels: git: link not to repository

#3177 Added TutorialEdge and links to both project series
  README.md
Labels: git: no conflicts resolved

#3072 Add Manduka to Enterprise Usage section
  README.md
Labels: git: no conflicts resolved

#3069 Example for a "Spotify client built with vue.js / vuex"
  README.md
Labels: git: no conflicts resolved

#3070 Added vue-async-gmaps package.
  README.md
Labels: git: no conflicts resolved

#3075 New Carousel addition!
  README.md
Labels: git: no conflicts resolved

#3076 Add @satmaxt/sidebar-menu-drawer
  README.md
Labels: git: no conflicts resolved

#3077 Added ZingChart's Vue component to Charts section
  README.md
Labels: git: no conflicts resolved

#3083 Update README.md
  README.md
Labels: git: no conflicts resolved

#3087 Update Readme
  README.md
Labels: git: no conflicts resolved

#3092 Added temp-mail.io
  README.md
Labels: git: no conflicts resolved

#3093 Update README.md
  README.md
Labels: git: no conflicts resolved

#3094 Add Vue-Date-Tools lightweight date components
  README.md
Labels: git: no conflicts resolved

#3096 Add FancyGrid in UI Components/Table section
  README.md
Labels: lists: not the last on the list

#3099 my plugin description have been updated, support for mobile. Please accept my pull request, thanks
  README.md
Labels: lists: not the last on the list

#3100 Added best-movies.watch to apps/websites list
  README.md
Labels: git: no conflicts resolved

#3101 Added CodeceptUI Vue app & CLI plugin
  README.md
Labels: git: no conflicts resolved

#3108 add vue-slick-carousel to component - carousel
  README.md
Labels: git: no conflicts resolved

#3111 Added Tune.pk in the list of Apps/Websites
  README.md
Labels: git: no conflicts resolved

#3112 added vuex-factories
  README.md
Labels: git: no conflicts resolved

#3121 Added vREST NG Link
  README.md
Labels: git: no conflicts resolved

#3127 add server-side rendering framework
  README.md
Labels: git: no conflicts resolved

#3249 add new component about audio. please~~~
  README.md
Labels: git: PR template structure broken

#3129 Add vue-kinesis
  README.md
Labels: git: no conflicts resolved

#3131 Add link to CZ/SK community
  README.md
Labels: git: no conflicts resolved

#3138 Add vue-interactive-paycard
  README.md
Labels: git: no conflicts resolved

#3147 Add vuedts (#3146)
  README.md
Labels: lists: not the last on the list

#3150 Add vue-heroicons and v-intersect
  README.md
Labels: git: broken PR

#3152 Added Vue Component Development Kit
  README.md
Labels: git: no conflicts resolved

#3159 Add vue-pivottable, vue-datamaps
  README.md
Labels: git: no conflicts resolved

#3178 Add Marked.cc to open source projects
  README.md
Labels: git: no conflicts resolved

#3181 Add CodeSandbox to Dev Tools
  README.md
Labels: git: no conflicts resolved

#3186 Added vue-form-generator to the Form Generators list
  README.md
Labels: git: no conflicts resolved

#3188 Updated README, added vue-anka-cropper
  README.md
Labels: git: no conflicts resolved

#3189 Add proper link to CoreUI Admin Template and add new UI components library
  README.md
Labels: git: no conflicts resolved

#3211 add jscharting-vue
  README.md
Labels: git: no conflicts resolved

#3213 Adds new video tutorial
  README.md
Labels: git: no conflicts resolved

#3247 Addition of Vue-Responsive-Dash
  README.md
Labels: git: PR template structure broken

#3212 Adds Vue Formulate to relevant lists
  README.md
Labels: git: no conflicts resolved
